### ISSUE TITLE
Backend Code errors at Terminal execution

### ISSUE THREAD

**Issue by luke-qk** [shrikhaparul/Ikart#22]
Partial log is pasted below for reference:
2023-10-10 17:14:21,447 | task_logger | MainProcess  | engine_main            | ERROR | error in  write() takes 3 positional arguments but 9 were given.
Traceback (most recent call last):
  File "/home/luke/Ikart-main/src/scripts/engine_main/engine_code.py", line 591, in engine_main
    value=write(json_data, i,counter,config_file_path,task_id,run_id,
TypeError: write() takes 3 positional arguments but 9 were given
2023-10-10 17:14:21,447 | task_logger | MainProcess  | execute_engine         | ERROR | error in executing engine write() takes 3 positional arguments but 9 were given.
Traceback (most recent call last):
  File "/home/luke/Ikart-main/download.py", line 286, in execute_engine
    engine_code.engine_main(prj_nm,task_name,config_path,run_id,file_path,iter_value)
  File "/home/luke/Ikart-main/src/scripts/engine_main/engine_code.py", line 760, in engine_main
    raise error
  File "/home/luke/Ikart-main/src/scripts/engine_main/engine_code.py", line 591, in engine_main
    value=write(json_data, i,counter,config_file_path,task_id,run_id,
TypeError: write() takes 3 positional arguments but 9 were given
2023-10-10 17:14:21,447 | root       | MainProcess  | execute_job            | ERROR | error in master_executor file write() takes 3 positional arguments but 9 were given.

**Comment by puneeths19** [comment]
The above issue got resolved.
The reason for the above error is not used latest engine code.
